name: cloud-services-plugin-status-gibsop1
label: gibsop1

description: |
  How to use cli commands in skillets

type: panorama
labels:
  collection:
    - Example Skillets
    
snippets:
  - name: system_object
    cmd: cli
    cmd_str: show system info
    outputs:
      - name: results_as_object
        capture_object: .
